#!/usr/bin/env bash

#
# What does this script ?
# Identify and display the ethernet interface setup :
# - Display the broadcast adress
# - Dsiplat all ip adresses from the same sub-network
#

# Get the ethernet network interface
# On macos, it is en0
readonly INTERFACE=$(ifconfig en0)

# No valid interface
if [ "$INTERFACE" == "" ]; then
  echo "No active ethernet interface"
  exit
fi

echo "$INTERFACE"

# Get broadcast adress
# [0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\
readonly BROADCAST=$(echo "$INTERFACE_WE_WANT" | sed -n -e "/broadcast/ s/.*broadcast //p")

# Adresse to
echo "BROADCAST : $BROADCAST"

# Get all ip adress  from the same subnetwork
echo "All ip adresses given from $BROADCAST"

# ARP is the protocol used to by the broadcast
# Each machine of the network is listening to the broadcast
# To communicate with a machine on the same network
# it asks the mac adress of the corresponding ip to the broadcast
# then the broadcast will ask each machine who it is
# and respond the mac adress you want
arp -n
