#!/usr/bin/env bash

#
# What does this script ?
# Identify and display the ethernet interface setup :
# - Display the broadcast adress
# - Dsiplat all ip adresses from the same sub-network
#

# Get all network interfaces
# -u limits this to interfaces that are up
readonly INTERFACES=$(ifconfig -ul)

INTERFACE_WE_WANT=""

# For each interface
for X in $INTERFACES
do
  XCONFIG=$(ifconfig $X)

  ETHER=$(echo $XCONFIG | grep ether)
  NAME=$(echo $XCONFIG | grep 'en[0-9]\+\:')
  ACTIVE=$(echo $XCONFIG | grep 'status: active')

  # echo "$XCONFIG"
  if [[ -z "$ETHER" ]] || [[ -z "$ACTIVE" ]] || [[ -z "$NAME" ]]; then
    # No valid interface
    echo -n
  else
    INTERFACE_WE_WANT="$XCONFIG"
  fi
done

# No valid interface
if [ "$INTERFACE_WE_WANT" == "" ]; then
  echo "No active ether interface"
  exit
fi

echo "$INTERFACE_WE_WANT"

# Get broadcast adress
# [0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\
readonly BROADCAST=$(echo "$INTERFACE_WE_WANT" | sed -n -e "/broadcast/ s/.*broadcast //p")

echo "BROADCAST : $BROADCAST"

# Get all ip adress  from the same subnetwork
echo "All ip adresses in $BROADCAST"

netstat -r BROADCAST
