#!/usr/bin/env bash

#
# What does this script ?
# Display only the login, the UID and the path of each file entry of /etc/passwd
# Structure of /etc/passwd file
# User name
# Encrypted password
# User ID number (UID)
# User's group ID number (GID)
# Full name of the user (GECOS)
# User home directory
# Login shell
#

set -e

readonly CONTENT=$(cat /etc/passwd)

for X in $CONTENT
do
	for Y in $X
	do
    	LOGIN_VAR=$(echo "$Y" | cut -d ':' -f1)
    	UID_VAR=$(echo "$Y" | cut -d ':' -f4)
    	PATH_VAR=$(echo "$Y" | rev | cut -d':' -f 1 | rev)
	done
	
	echo "$LOGIN_VAR:$UID_VAR:$PATH_VAR"
done
