#!/bin/bash

#
# What does this script ?
# Update package every zeek and log it
#

#
# CONFIGURATION VARIABLE
#

set -e

# Get date informations

# Set a new line variable
readonly RET="=============================="


# Store the package list update command
readonly UPDATE_LOG_PATH="/var/log/update_script.log"

# Store the package update commandi - option y to overpass confirmation
readonly UPGRADE_LOG_PATH="/var/log/update_script.log"

#
## Script execution
#

readonly DATE=$(date +"%m-%d-%y")
readonly HOUR=$(date +"%r")

# Concat date informations
readonly TIME="$RET The $DATE at $HOUR $RET"

# Update
# Format the top of a new insert
echo $TIME >> "$UPDATE_LOG_PATH"

apt-get update >> "$UPDATE_LOG_PATH"

# Upgrade
apt-get upgrade -y >> $UPGRADE_LOG_PATH

#
# Cron handling
#

# Open the crontab modification
crontab -e

# Execute on every week
readonly PATH="$(cd "$(dirname "$0")" && pwd)/03"
readonly RULE="@weekly $PATH"

# Append to cron task only if no exist
if [ -z $(crontab -l | grep $RULE) ]; then
  echo $RULE | crontab -
fi

echo "DONE !"
