#!/usr/bin/env bash

#
# What does this script ?
# Change th display on the screen
#

set -e

readonly MODE=1366x768

# No arguments supplied
if [ $# -eq 0 ] ;then
    echo "No arguments supplied"
    exit
fi

readonly ASK=$(echo $1 | tr '[A-Z]' '[a-z]')

if [ -z "$DISPLAY" ]; then
  echo "DISPLAY variable is not set"
  exit
fi

# Detect monitors
readonly MONITORS=$(xrandr --listmonitors)

readonly MONITOR_NUMBER=$(echo "$MONITORS" | head -1 | rev | cut -d' ' -f 1 | rev)
readonly MONITOR1=$(echo "$MONITORS" | tail -n+2 | head -1 | rev | cut -d' ' -f 1 | rev)

# Detect if second monitor
if [ $MONITOR_NUMBER -gt 2 ]; then
  readonly MONITOR2=$(echo "$MONITORS" | tail -n+3 | head -1 | rev | cut -d' ' -f 1 | rev)
fi

if [ $ASK == "landscape" ] ;then
        xrandr --output "$MONITOR1" --mode $MODE --rotate normal
        if [ $MONITOR_NUMBER -gt 2 ]; then
          xrandr --output "$MONITOR2" --off
        fi
elif [ $ASK == "portrait" ] ;then
        xrandr --output "$MONITOR1" --mode $MODE --rotate left
        if [ $MONITOR_NUMBER -gt 2 ]; then
          xrandr --output "$MONITOR2" --off
        fi
elif [[ $ASK == "horizon" ]] && [[ $MONITOR_NUMBER -gt 2 ]] ;then
        xrandr --output "$MONITOR1" --mode $MODE --rotate normal
        xrandr --output "$MONITOR2" --mode $MODE --rotate normal --right-of "$MONITOR1"
elif [[ $ASK == "zenith" ]] && [[ $MONITOR_NUMBER -gt 2 ]] ;then
        xrandr --output "$MONITOR1" --mode $MODE --rotate left
        xrandr --output "$MONITOR2" --mode $MODE --rotate left --below "$MONITOR1"
else
        echo "Unknown display"
        exit
fi

echo "$ASK"
